-- ============================================================
-- DOLDOL ADMIN CONTROL CENTER v3
-- Supabase SQL Editor에서 1회 실행
-- ============================================================
create table if not exists public.admin_logs (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null references auth.users(id) on delete cascade,
  action text not null, target_user_id uuid, details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.admin_logs enable row level security;

create or replace function public.admin_is_authorized()
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.users where user_id=auth.uid() and is_admin=true and coalesce(user_level,0)>=10); $$;

create or replace function public.admin_log(p_action text,p_target uuid,p_details jsonb default '{}'::jsonb)
returns void language plpgsql security definer set search_path=public as $$
begin
 if not public.admin_is_authorized() then raise exception '관리자 권한이 없습니다.'; end if;
 insert into public.admin_logs(admin_user_id,action,target_user_id,details) values(auth.uid(),p_action,p_target,coalesce(p_details,'{}'::jsonb));
end $$;

-- 회원 상태/계정 인증 정보까지 관리자 전용으로 조회
create or replace function public.admin_list_users()
returns setof jsonb language plpgsql security definer set search_path=public as $$
begin
 if not public.admin_is_authorized() then raise exception '관리자 권한이 없습니다.'; end if;
 return query
 select to_jsonb(u) || jsonb_build_object(
   'auth_email',a.email,
   'auth_created_at',a.created_at,
   'auth_confirmed_at',a.email_confirmed_at,
   'last_sign_in_at',a.last_sign_in_at,
   'banned_until',a.banned_until,
   'auth_role',a.role
 ) from public.users u join auth.users a on a.id=u.user_id order by u.user_number nulls last;
end $$;

create or replace function public.admin_get_user_detail(p_user_id uuid)
returns setof jsonb language plpgsql security definer set search_path=public as $$
begin
 if not public.admin_is_authorized() then raise exception '관리자 권한이 없습니다.'; end if;
 return query select to_jsonb(u) || jsonb_build_object(
   'auth_email',a.email,'auth_created_at',a.created_at,'auth_confirmed_at',a.email_confirmed_at,
   'last_sign_in_at',a.last_sign_in_at,'banned_until',a.banned_until,'auth_role',a.role
 ) from public.users u join auth.users a on a.id=u.user_id where u.user_id=p_user_id;
end $$;

-- users 컬럼은 프로젝트에서 사용 중인 핵심 관리 필드를 명시적으로 허용
create or replace function public.admin_update_user_full(p_user_id uuid,p_payload jsonb)
returns void language plpgsql security definer set search_path=public as $$
declare v jsonb:=coalesce(p_payload,'{}'::jsonb);
begin
 if not public.admin_is_authorized() then raise exception '관리자 권한이 없습니다.'; end if;
 update public.users set
   name=coalesce(v->>'name',name),
   profile_image=coalesce(v->>'profile_image',profile_image),
   user_level=case when v ? 'user_level' then (v->>'user_level')::integer else user_level end,
   doldolcoin=case when v ? 'doldolcoin' then (v->>'doldolcoin')::bigint else doldolcoin end,
   exp=case when v ? 'exp' then (v->>'exp')::bigint else exp end,
   equipped_title=coalesce(v->>'equipped_title',equipped_title),
   user_achievement=case when v ? 'user_achievement' then v->'user_achievement' else user_achievement end,
   read_dori_news=case when v ? 'read_dori_news' then (v->>'read_dori_news')::integer else read_dori_news end,
   quiz_right=case when v ? 'quiz_right' then (v->>'quiz_right')::integer else quiz_right end,
   quiz_news_number=case when v ? 'quiz_news_number' then (v->>'quiz_news_number')::integer else quiz_news_number end,
   quiz_answered=case when v ? 'quiz_answered' then (v->>'quiz_answered')::integer else quiz_answered end,
   quiz_answers=case when v ? 'quiz_answers' then v->'quiz_answers' else quiz_answers end,
   is_admin=case when v ? 'is_admin' then (v->>'is_admin')::boolean else is_admin end,
   suspended_until=case when v ? 'suspended_until' then nullif(v->>'suspended_until','')::timestamptz else suspended_until end,
   permanently_banned=case when v ? 'permanently_banned' then (v->>'permanently_banned')::boolean else permanently_banned end,
   suspension_reason=case when v ? 'suspension_reason' then v->>'suspension_reason' else suspension_reason end
 where user_id=p_user_id;
 perform public.admin_log('USER_FULL_UPDATE',p_user_id,v - 'user_id' - 'login_id' - 'user_number' - 'created_at');
end $$;

alter table public.users add column if not exists suspended_until timestamptz;
alter table public.users add column if not exists permanently_banned boolean not null default false;
alter table public.users add column if not exists suspension_reason text;

-- 코인 원장: 관리자 지급/차감 및 일반적인 잔액 변동을 추적
create table if not exists public.doldolcoin_transactions(
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 amount bigint not null,
 balance_after bigint,
 reason text not null default '잔액 변경',
 admin_user_id uuid references auth.users(id) on delete set null,
 source text not null default 'admin',
 created_at timestamptz not null default now()
);
create index if not exists doldolcoin_transactions_user_idx on public.doldolcoin_transactions(user_id,created_at desc);
alter table public.doldolcoin_transactions enable row level security;

create or replace function public.track_coin_change()
returns trigger language plpgsql security definer set search_path=public as $$
declare delta bigint; reason_text text; source_text text; admin_id uuid;
begin
 delta:=coalesce(new.doldolcoin,0)-coalesce(old.doldolcoin,0);
 if delta=0 then return new; end if;
 reason_text:=coalesce(current_setting('doldol.coin_reason',true),'잔액 변경');
 source_text:=coalesce(current_setting('doldol.coin_source',true),'system');
 admin_id:=auth.uid();
 insert into public.doldolcoin_transactions(user_id,amount,balance_after,reason,admin_user_id,source)
 values(new.user_id,delta,new.doldolcoin,reason_text,admin_id,source_text);
 return new;
end $$;
drop trigger if exists trg_track_coin_change on public.users;
create trigger trg_track_coin_change after update of doldolcoin on public.users
for each row execute function public.track_coin_change();

create or replace function public.admin_adjust_coins(p_user_id uuid,p_amount bigint,p_reason text)
returns void language plpgsql security definer set search_path=public as $$
declare new_balance bigint;
begin
 if not public.admin_is_authorized() then raise exception '관리자 권한이 없습니다.'; end if;
 update public.users set doldolcoin=coalesce(doldolcoin,0)+p_amount where user_id=p_user_id returning doldolcoin into new_balance;
 if not found then raise exception '회원을 찾을 수 없습니다.'; end if;
 perform set_config('doldol.coin_reason',coalesce(p_reason,'관리자 조정'),true);
 perform set_config('doldol.coin_source','admin',true);
 perform public.admin_log('COIN_ADJUST',p_user_id,jsonb_build_object('amount',p_amount,'reason',p_reason,'balance_after',new_balance));
end $$;

create or replace function public.admin_update_user(p_user_id uuid,p_doldolcoin bigint,p_exp bigint,p_user_level integer)
returns void language plpgsql security definer set search_path=public as $$
begin
 perform public.admin_update_user_full(p_user_id,jsonb_build_object('doldolcoin',p_doldolcoin,'exp',p_exp,'user_level',p_user_level));
end $$;

create or replace function public.admin_suspend_user(p_user_id uuid,p_until timestamptz,p_permanent boolean,p_reason text)
returns void language plpgsql security definer set search_path=public as $$
begin
 if not public.admin_is_authorized() then raise exception '관리자 권한이 없습니다.'; end if;
 update public.users set suspended_until=p_until,permanently_banned=p_permanent,suspension_reason=p_reason where user_id=p_user_id;
 perform public.admin_log('USER_SUSPEND',p_user_id,jsonb_build_object('until',p_until,'permanent',p_permanent,'reason',p_reason));
end $$;

-- 관리자용 CRUD 정책
do $$
declare t text;
begin
 foreach t in array array['users','rockey_news','dori_box_items','rockey_news_events','admin_logs','doldolcoin_transactions'] loop
   if to_regclass('public.'||t) is not null then
     execute format('alter table public.%I enable row level security',t);
   end if;
 end loop;
end $$;

do $$ begin
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='users' and policyname='admin read all users') then
  create policy "admin read all users" on public.users for select to authenticated using(public.admin_is_authorized() or user_id=auth.uid());
 end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='rockey_news' and policyname='admin all news') then
  create policy "admin all news" on public.rockey_news for all to authenticated using(public.admin_is_authorized()) with check(public.admin_is_authorized());
 end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='dori_box_items' and policyname='admin all box') then
  create policy "admin all box" on public.dori_box_items for all to authenticated using(public.admin_is_authorized()) with check(public.admin_is_authorized());
 end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='rockey_news_events' and policyname='admin all events') then
  create policy "admin all events" on public.rockey_news_events for all to authenticated using(public.admin_is_authorized()) with check(public.admin_is_authorized());
 end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='admin_logs' and policyname='admin read logs') then
  create policy "admin read logs" on public.admin_logs for select to authenticated using(public.admin_is_authorized());
 end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='doldolcoin_transactions' and policyname='admin read coin ledger') then
  create policy "admin read coin ledger" on public.doldolcoin_transactions for select to authenticated using(public.admin_is_authorized());
 end if;
end $$;

revoke all on function public.admin_list_users() from public;
revoke all on function public.admin_get_user_detail(uuid) from public;
revoke all on function public.admin_update_user_full(uuid,jsonb) from public;
revoke all on function public.admin_update_user(uuid,bigint,bigint,integer) from public;
revoke all on function public.admin_adjust_coins(uuid,bigint,text) from public;
revoke all on function public.admin_suspend_user(uuid,timestamptz,boolean,text) from public;
grant execute on function public.admin_list_users() to authenticated;
grant execute on function public.admin_get_user_detail(uuid) to authenticated;
grant execute on function public.admin_update_user_full(uuid,jsonb) to authenticated;
grant execute on function public.admin_update_user(uuid,bigint,bigint,integer) to authenticated;
grant execute on function public.admin_adjust_coins(uuid,bigint,text) to authenticated;
grant execute on function public.admin_suspend_user(uuid,timestamptz,boolean,text) to authenticated;
