-- ============================================================
-- 돌이 관리자 센터
-- 관리자 이메일 2단계 인증 DB 구성
-- ============================================================
-- 전제:
--   public.users.user_id = auth.users.id
--   public.users.is_admin = true
--   public.users.user_level >= 10
--
-- 이 파일은 안전하게 여러 번 실행할 수 있도록 작성했습니다.
-- service_role만 인증 토큰 테이블을 직접 관리합니다.
-- ============================================================

create table if not exists public.admin_verification_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  token text not null,
  expires_at timestamptz not null,
  used boolean not null default false,
  created_at timestamptz not null default now()
);

-- 기존 테이블을 사용하는 경우에도 필요한 인덱스/제약을 보강합니다.
create unique index if not exists
  admin_verification_tokens_token_uidx
on public.admin_verification_tokens(token);

create index if not exists
  admin_verification_tokens_user_id_idx
on public.admin_verification_tokens(user_id);

create index if not exists
  admin_verification_tokens_expires_at_idx
on public.admin_verification_tokens(expires_at);

alter table public.admin_verification_tokens enable row level security;

-- 클라이언트(anon/authenticated)는 토큰을 직접 읽거나 쓸 수 없습니다.
revoke all on table public.admin_verification_tokens from anon, authenticated;

-- Edge Function은 service_role로 접근합니다.
grant all on table public.admin_verification_tokens to service_role;

-- identity sequence 사용 권한(환경에 따라 이미 존재해도 안전합니다).
grant usage, select on sequence public.admin_verification_tokens_id_seq to service_role;

-- 만료/사용 완료 토큰 정리용 함수.
create or replace function public.cleanup_admin_verification_tokens()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.admin_verification_tokens
  where expires_at < now()
     or (used = true and created_at < now() - interval '1 day');
end;
$$;

revoke all on function public.cleanup_admin_verification_tokens() from public;
grant execute on function public.cleanup_admin_verification_tokens() to service_role;

-- 현재 남아 있는 만료 토큰을 즉시 정리합니다.
select public.cleanup_admin_verification_tokens();

-- 확인
select
  column_name,
  data_type,
  is_nullable
from information_schema.columns
where table_schema = 'public'
  and table_name = 'admin_verification_tokens'
order by ordinal_position;
