-- ============================================================
-- 돌이 관리자 센터 - 회원 전체 조회/관리 확장판
-- ============================================================
-- 핵심 원칙
-- 1) 관리자 사이트 진입: is_admin=true AND user_level>=10
-- 2) 회원 목록 조회: public.users 전체를 조회
-- 3) auth.users는 LEFT JOIN하여 Auth 계정이 없는 users 행도 유지
-- 4) Auth 민감정보는 SECURITY DEFINER 함수가 필요한 필드만 반환
-- 5) service_role key는 브라우저에 노출하지 않음
-- ============================================================

create table if not exists public.admin_logs (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  target_user_id uuid,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.admin_logs enable row level security;

drop policy if exists "admins read admin logs" on public.admin_logs;
create policy "admins read admin logs" on public.admin_logs
for select to authenticated
using (public.admin_is_authorized());

create or replace function public.admin_is_authorized()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.users u
    where u.user_id = auth.uid()
      and u.is_admin = true
      and coalesce(u.user_level, 0) >= 10
  );
$$;

revoke all on function public.admin_is_authorized() from public;
grant execute on function public.admin_is_authorized() to authenticated;

-- ============================================================
-- 전체 회원 조회
-- ============================================================
-- 관리자 본인을 포함한 모든 public.users 행을 반환합니다.
-- is_admin/user_level로 회원을 걸러내지 않습니다.
-- auth.users가 없더라도 LEFT JOIN 때문에 users 행은 남습니다.
-- ============================================================

drop function if exists public.admin_list_users(text, integer, integer);
create or replace function public.admin_list_users(
  p_search text default null,
  p_limit integer default 500,
  p_offset integer default 0
)
returns table (
  user_id uuid,
  user_number bigint,
  login_id text,
  name text,
  profile_image text,
  user_level integer,
  doldolcoin bigint,
  exp bigint,
  exp_level integer,
  equipped_title text,
  is_admin boolean,
  suspended_until timestamptz,
  permanently_banned boolean,
  suspension_reason text,
  auth_user_id uuid,
  email text,
  email_confirmed_at timestamptz,
  last_sign_in_at timestamptz,
  auth_created_at timestamptz,
  last_seen_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    u.user_id,
    u.user_number,
    u.login_id,
    u.name,
    u.profile_image,
    u.user_level,
    coalesce(u.doldolcoin, 0),
    coalesce(u.exp, 0),
    u.exp_level,
    u.equipped_title,
    coalesce(u.is_admin, false),
    u.suspended_until,
    coalesce(u.permanently_banned, false),
    u.suspension_reason,
    a.id,
    a.email::text,
    a.email_confirmed_at,
    a.last_sign_in_at,
    a.created_at,
    a.last_sign_in_at
  from public.users u
  left join auth.users a on a.id = u.user_id
  where
    p_search is null
    or trim(p_search) = ''
    or u.login_id ilike '%' || p_search || '%'
    or u.name ilike '%' || p_search || '%'
    or a.email ilike '%' || p_search || '%'
    or cast(u.user_number as text) = trim(p_search)
  order by u.user_number nulls last, u.login_id nulls last
  limit greatest(1, least(coalesce(p_limit, 500), 1000))
  offset greatest(coalesce(p_offset, 0), 0);
$$;

revoke all on function public.admin_list_users(text, integer, integer) from public;
grant execute on function public.admin_list_users(text, integer, integer) to authenticated;

-- ============================================================
-- 회원 상세 조회
-- ============================================================

drop function if exists public.admin_get_user_detail(uuid);
create or replace function public.admin_get_user_detail(p_user_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  result jsonb;
begin
  if not public.admin_is_authorized() then
    raise exception '관리자 권한이 없습니다.';
  end if;

  select jsonb_build_object(
    'profile', to_jsonb(u),
    'auth', case when a.id is null then null else jsonb_build_object(
      'id', a.id,
      'email', a.email,
      'email_confirmed_at', a.email_confirmed_at,
      'last_sign_in_at', a.last_sign_in_at,
      'created_at', a.created_at,
      'updated_at', a.updated_at
    ) end
  )
  into result
  from public.users u
  left join auth.users a on a.id = u.user_id
  where u.user_id = p_user_id;

  return result;
end;
$$;

revoke all on function public.admin_get_user_detail(uuid) from public;
grant execute on function public.admin_get_user_detail(uuid) to authenticated;

-- ============================================================
-- 회원 관리 필드
-- ============================================================

alter table public.users add column if not exists suspended_until timestamptz;
alter table public.users add column if not exists permanently_banned boolean not null default false;
alter table public.users add column if not exists suspension_reason text;

create or replace function public.admin_update_user(
  p_user_id uuid,
  p_doldolcoin bigint,
  p_exp bigint,
  p_user_level integer
) returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  if not public.admin_is_authorized() then
    raise exception '관리자 권한이 없습니다.';
  end if;

  update public.users
  set doldolcoin = p_doldolcoin,
      exp = p_exp,
      user_level = p_user_level
  where user_id = p_user_id;

  if not found then
    raise exception '회원을 찾을 수 없습니다.';
  end if;

  insert into public.admin_logs(admin_user_id, action, target_user_id, details)
  values (
    auth.uid(),
    'USER_UPDATE',
    p_user_id,
    jsonb_build_object('coins',p_doldolcoin,'exp',p_exp,'level',p_user_level)
  );
end;
$$;

create or replace function public.admin_adjust_coins(
  p_user_id uuid,
  p_amount bigint,
  p_reason text
) returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  if not public.admin_is_authorized() then
    raise exception '관리자 권한이 없습니다.';
  end if;

  update public.users
  set doldolcoin = coalesce(doldolcoin,0) + p_amount
  where user_id = p_user_id;

  if not found then
    raise exception '회원을 찾을 수 없습니다.';
  end if;

  insert into public.admin_logs(admin_user_id,action,target_user_id,details)
  values(
    auth.uid(),
    'COIN_ADJUST',
    p_user_id,
    jsonb_build_object('amount',p_amount,'reason',coalesce(p_reason,''))
  );
end;
$$;

create or replace function public.admin_suspend_user(
  p_user_id uuid,
  p_until timestamptz,
  p_permanent boolean,
  p_reason text
) returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  if not public.admin_is_authorized() then
    raise exception '관리자 권한이 없습니다.';
  end if;

  update public.users
  set suspended_until = p_until,
      permanently_banned = p_permanent,
      suspension_reason = p_reason
  where user_id = p_user_id;

  if not found then
    raise exception '회원을 찾을 수 없습니다.';
  end if;

  insert into public.admin_logs(admin_user_id,action,target_user_id,details)
  values(
    auth.uid(),
    'USER_SUSPEND',
    p_user_id,
    jsonb_build_object('until',p_until,'permanent',p_permanent,'reason',coalesce(p_reason,''))
  );
end;
$$;

revoke all on function public.admin_update_user(uuid,bigint,bigint,integer) from public;
revoke all on function public.admin_adjust_coins(uuid,bigint,text) from public;
revoke all on function public.admin_suspend_user(uuid,timestamptz,boolean,text) from public;
grant execute on function public.admin_update_user(uuid,bigint,bigint,integer) to authenticated;
grant execute on function public.admin_adjust_coins(uuid,bigint,text) to authenticated;
grant execute on function public.admin_suspend_user(uuid,timestamptz,boolean,text) to authenticated;

-- ============================================================
-- 돌돌코인 원장
-- ============================================================

create table if not exists public.doldolcoin_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  amount bigint not null,
  balance_after bigint,
  reason text not null default '',
  source text not null default 'unknown',
  actor_user_id uuid,
  created_at timestamptz not null default now()
);

create index if not exists doldolcoin_transactions_user_idx
on public.doldolcoin_transactions(user_id, created_at desc);

alter table public.doldolcoin_transactions enable row level security;

drop policy if exists "admins read coin ledger" on public.doldolcoin_transactions;
create policy "admins read coin ledger" on public.doldolcoin_transactions
for select to authenticated
using (public.admin_is_authorized());

create or replace function public.log_doldolcoin_change()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  if coalesce(new.doldolcoin,0) is distinct from coalesce(old.doldolcoin,0) then
    insert into public.doldolcoin_transactions(
      user_id, amount, balance_after, reason, source, actor_user_id
    ) values (
      new.user_id,
      coalesce(new.doldolcoin,0) - coalesce(old.doldolcoin,0),
      coalesce(new.doldolcoin,0),
      '돌돌코인 잔액 변경',
      'users_update',
      auth.uid()
    );
  end if;
  return new;
end;
$$;

drop trigger if exists trg_log_doldolcoin_change on public.users;
create trigger trg_log_doldolcoin_change
after update of doldolcoin on public.users
for each row execute function public.log_doldolcoin_change();

revoke all on table public.doldolcoin_transactions from anon;
grant select on table public.doldolcoin_transactions to authenticated;

-- ============================================================
-- 확인용 조회
-- ============================================================
select count(*) as total_users from public.users;
