-- ============================================================
-- 돌이 이슈 + 돌돌증권 연동
-- ============================================================
-- 역할
-- 1) 관리자가 돌이 이슈를 생성한다.
-- 2) 이슈 본문과 6개 종목의 영향률을 서버에 저장한다.
-- 3) 생성과 동시에 6개 종목의 현재가/가격 이력을 원자적으로 갱신한다.
-- 4) 브라우저에서는 직접 INSERT/UPDATE하지 않고 SECURITY DEFINER RPC만 호출한다.
--
-- 전제: 기존 돌돌증권 테이블
-- public.dori_stocks
-- public.dori_stock_prices
-- public.admin_logs
-- public.admin_is_authorized()
-- 가 이미 존재해야 합니다.
-- ============================================================

create table if not exists public.dori_stock_issues (
  id bigint generated by default as identity primary key,
  issue_number bigint generated by default as identity,
  title text not null,
  content text not null,
  status text not null default 'published'
    check (status in ('published', 'cancelled')),
  created_by text not null,
  created_at timestamptz not null default now(),
  published_at timestamptz not null default now(),
  constraint dori_stock_issues_issue_number_key unique (issue_number)
);

create table if not exists public.dori_stock_issue_impacts (
  id bigint generated by default as identity primary key,
  issue_id bigint not null
    references public.dori_stock_issues(id)
    on delete cascade,
  stock_id bigint not null
    references public.dori_stocks(id)
    on delete restrict,
  ticker text not null,
  change_percent numeric(7,2) not null
    check (change_percent between -50 and 50),
  old_price bigint not null,
  new_price bigint not null,
  created_at timestamptz not null default now(),
  constraint dori_stock_issue_impacts_issue_stock_key
    unique (issue_id, stock_id)
);

create index if not exists idx_dori_stock_issues_created_at
  on public.dori_stock_issues(created_at desc);

create index if not exists idx_dori_stock_issue_impacts_issue_id
  on public.dori_stock_issue_impacts(issue_id);

create index if not exists idx_dori_stock_issue_impacts_stock_id
  on public.dori_stock_issue_impacts(stock_id);

alter table public.dori_stock_issues enable row level security;
alter table public.dori_stock_issue_impacts enable row level security;

drop policy if exists "public read published dori stock issues"
  on public.dori_stock_issues;

create policy "public read published dori stock issues"
on public.dori_stock_issues
for select
to anon, authenticated
using (status = 'published');

drop policy if exists "public read dori stock issue impacts"
  on public.dori_stock_issue_impacts;

create policy "public read dori stock issue impacts"
on public.dori_stock_issue_impacts
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.dori_stock_issues i
    where i.id = issue_id
      and i.status = 'published'
  )
);

revoke all on public.dori_stock_issues from anon, authenticated;
revoke all on public.dori_stock_issue_impacts from anon, authenticated;

grant select on public.dori_stock_issues to anon, authenticated;
grant select on public.dori_stock_issue_impacts to anon, authenticated;

-- ============================================================
-- 관리자 이슈 생성 RPC
-- ============================================================

create or replace function public.admin_create_dori_stock_issue(
  p_title text,
  p_content text,
  p_impacts jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_issue_id bigint;
  v_issue_number bigint;
  v_user_id text;
  v_count integer;
  v_distinct integer;
  v_item record;
  v_stock record;
  v_pct numeric;
  v_new_price bigint;
begin
  -- 관리자 여부는 서버에서 다시 검사합니다.
  if not public.admin_is_authorized() then
    raise exception '관리자 권한이 없습니다.';
  end if;

  v_user_id := auth.uid()::text;

  if nullif(trim(coalesce(p_title, '')), '') is null then
    raise exception '이슈 제목을 입력하세요.';
  end if;

  if nullif(trim(coalesce(p_content, '')), '') is null then
    raise exception '이슈 내용을 입력하세요.';
  end if;

  if p_impacts is null or jsonb_typeof(p_impacts) <> 'array' then
    raise exception '주식 영향 데이터가 올바르지 않습니다.';
  end if;

  -- 반드시 6개 종목이고 중복이 없어야 합니다.
  select count(*), count(distinct stock_id)
    into v_count, v_distinct
  from jsonb_to_recordset(p_impacts)
    as x(
      stock_id bigint,
      ticker text,
      change_percent numeric
    );

  if v_count <> 6 or v_distinct <> 6 then
    raise exception '6개 종목의 영향률을 모두 입력해야 합니다.';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(p_impacts)
      as x(
        stock_id bigint,
        ticker text,
        change_percent numeric
      )
    where change_percent is null
       or change_percent < -50
       or change_percent > 50
  ) then
    raise exception '증감률은 -50.00%에서 50.00% 사이여야 합니다.';
  end if;

  -- 이슈 생성과 주가 반영은 하나의 트랜잭션으로 처리됩니다.
  -- 중간에 하나라도 실패하면 전체가 롤백됩니다.
  insert into public.dori_stock_issues (
    title,
    content,
    status,
    created_by
  )
  values (
    trim(p_title),
    trim(p_content),
    'published',
    v_user_id
  )
  returning id, issue_number
  into v_issue_id, v_issue_number;

  -- stock_id 순으로 잠가 동시 발행 시 교착 가능성을 낮춥니다.
  for v_item in
    select *
    from jsonb_to_recordset(p_impacts)
      as x(
        stock_id bigint,
        ticker text,
        change_percent numeric
      )
    order by stock_id
  loop

    select
      id,
      ticker,
      current_price
    into v_stock
    from public.dori_stocks
    where id = v_item.stock_id
      and is_active = true
    for update;

    if not found then
      raise exception
        '활성 종목을 찾을 수 없습니다. stock_id=%',
        v_item.stock_id;
    end if;

    if v_stock.ticker <> v_item.ticker then
      raise exception
        '종목 정보가 일치하지 않습니다. stock_id=%',
        v_item.stock_id;
    end if;

    v_pct := round(v_item.change_percent::numeric, 2);

    -- 현재가 × (1 + 증감률/100)
    -- 주가는 최소 1 돌돌코인으로 제한합니다.
    v_new_price := greatest(
      1,
      round(
        v_stock.current_price::numeric
        * (1 + v_pct / 100.0)
      )::bigint
    );

    update public.dori_stocks
    set
      previous_price = current_price,
      current_price = v_new_price,
      change_amount = v_new_price - current_price,
      change_percent = v_pct
    where id = v_stock.id;

    insert into public.dori_stock_prices (
      stock_id,
      price,
      previous_price,
      change_amount,
      change_percent,
      reason
    )
    values (
      v_stock.id,
      v_new_price,
      v_stock.current_price,
      v_new_price - v_stock.current_price,
      v_pct,
      '돌이 이슈 #' || v_issue_number || ': ' || trim(p_title)
    );

    insert into public.dori_stock_issue_impacts (
      issue_id,
      stock_id,
      ticker,
      change_percent,
      old_price,
      new_price
    )
    values (
      v_issue_id,
      v_stock.id,
      v_stock.ticker,
      v_pct,
      v_stock.current_price,
      v_new_price
    );

  end loop;

  insert into public.admin_logs (
    admin_user_id,
    action,
    target_user_id,
    details
  )
  values (
    auth.uid(),
    'DORI_STOCK_ISSUE_CREATE',
    null,
    jsonb_build_object(
      'issue_id', v_issue_id,
      'issue_number', v_issue_number,
      'title', trim(p_title),
      'impacts', p_impacts
    )
  );

  return v_issue_id;
end;
$$;

revoke all on function public.admin_create_dori_stock_issue(
  text,
  text,
  jsonb
) from public;

grant execute on function public.admin_create_dori_stock_issue(
  text,
  text,
  jsonb
) to authenticated;

notify pgrst, 'reload schema';
