-- 돌이 관리자 센터 보안/관리 SQL
-- 중요: Supabase Auth의 비밀번호는 users 테이블에 평문으로 저장하지 않습니다.
-- 이 스크립트는 기존 users 테이블(user_id UUID, login_id, user_level, is_admin 등)을 전제로 합니다.

create table if not exists public.admin_logs (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  target_user_id uuid,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.admin_logs enable row level security;

-- 관리자만 자신의 관리자 로그를 읽을 수 있도록 함.
create policy "admins read admin logs" on public.admin_logs
for select to authenticated
using (
  exists (
    select 1 from public.users u
    where u.user_id = auth.uid()
      and u.is_admin = true
      and coalesce(u.user_level,0) >= 10
  )
);

create or replace function public.admin_is_authorized()
returns boolean language sql stable security definer set search_path=public
as $$
  select exists (
    select 1 from public.users
    where user_id = auth.uid()
      and is_admin = true
      and coalesce(user_level,0) >= 10
  );
$$;

-- login_id + password를 검증하는 부분은 Auth의 password verifier를 직접 SQL에서 구현하면 안 됩니다.
-- 따라서 Edge Function에서 login_id -> Auth email을 확인한 뒤 signInWithPassword를 수행하거나,
-- 별도의 안전한 서버측 인증 흐름을 사용하세요.
-- 아래 RPC는 현재 인증 세션이 이미 만들어진 뒤 관리자 여부를 재확인하는 용도입니다.

create or replace function public.admin_update_user(
  p_user_id uuid,
  p_doldolcoin bigint,
  p_exp bigint,
  p_user_level integer
) returns void
language plpgsql security definer set search_path=public
as $$
begin
  if not public.admin_is_authorized() then raise exception '관리자 권한이 없습니다.'; end if;
  update public.users
  set doldolcoin=p_doldolcoin, exp=p_exp, user_level=p_user_level
  where user_id=p_user_id;
  insert into public.admin_logs(admin_user_id,action,target_user_id,details)
  values(auth.uid(),'USER_UPDATE',p_user_id,jsonb_build_object('coins',p_doldolcoin,'exp',p_exp,'level',p_user_level));
end $$;

create or replace function public.admin_adjust_coins(
  p_user_id uuid,
  p_amount bigint,
  p_reason text
) returns void
language plpgsql security definer set search_path=public
as $$
begin
  if not public.admin_is_authorized() then raise exception '관리자 권한이 없습니다.'; end if;
  update public.users set doldolcoin=coalesce(doldolcoin,0)+p_amount where user_id=p_user_id;
  insert into public.admin_logs(admin_user_id,action,target_user_id,details)
  values(auth.uid(),'COIN_ADJUST',p_user_id,jsonb_build_object('amount',p_amount,'reason',p_reason));
end $$;

-- 영구/일시 정지는 실제 로그인 차단까지 연결하려면 별도 상태 컬럼과
-- Edge Function/Auth hook 또는 애플리케이션 로그인 정책을 추가해야 합니다.
alter table public.users add column if not exists suspended_until timestamptz;
alter table public.users add column if not exists permanently_banned boolean not null default false;
alter table public.users add column if not exists suspension_reason text;

create or replace function public.admin_suspend_user(
  p_user_id uuid, p_until timestamptz, p_permanent boolean, p_reason text
) returns void
language plpgsql security definer set search_path=public
as $$
begin
  if not public.admin_is_authorized() then raise exception '관리자 권한이 없습니다.'; end if;
  update public.users set suspended_until=p_until, permanently_banned=p_permanent, suspension_reason=p_reason where user_id=p_user_id;
  insert into public.admin_logs(admin_user_id,action,target_user_id,details)
  values(auth.uid(),'USER_SUSPEND',p_user_id,jsonb_build_object('until',p_until,'permanent',p_permanent,'reason',p_reason));
end $$;

revoke all on function public.admin_update_user(uuid,bigint,bigint,integer) from public;
revoke all on function public.admin_adjust_coins(uuid,bigint,text) from public;
revoke all on function public.admin_suspend_user(uuid,timestamptz,boolean,text) from public;
grant execute on function public.admin_update_user(uuid,bigint,bigint,integer) to authenticated;
grant execute on function public.admin_adjust_coins(uuid,bigint,text) to authenticated;
grant execute on function public.admin_suspend_user(uuid,timestamptz,boolean,text) to authenticated;
