create table if not exists public.admin_verification_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  token text not null unique,
  expires_at timestamptz not null,
  used boolean not null default false,
  created_at timestamptz not null default now()
);
alter table public.admin_verification_tokens enable row level security;
-- 토큰 검증/소비는 Edge Function(service role)에서 처리합니다.
-- 클라이언트에는 SELECT/INSERT 정책을 주지 않습니다.
revoke all on public.admin_verification_tokens from anon, authenticated;