const cfg=window.DORI_ADMIN_CONFIG||{}; const sb=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY); const $=s=>document.querySelector(s);
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
function toast(m,ok=true){const e=$("#toast");if(!e)return;e.textContent=m;e.className=ok?"show ok":"show";clearTimeout(window.__t);window.__t=setTimeout(()=>e.className="",2800)}
async function requireAdmin(){const {data,error}=await sb.auth.getSession();if(error||!data.session?.user)throw new Error("관리자 로그인 세션이 없습니다.");const {data:p,error:e}=await sb.from("users").select("is_admin,user_level,name").eq("user_id",String(data.session.user.id)).single();if(e)throw e;if(p?.is_admin!==true||Number(p.user_level||0)<10)throw new Error("관리자 권한이 없습니다.");}
const idParam=()=>new URLSearchParams(location.search).get("id"); const isNew=()=>new URLSearchParams(location.search).get("new")==="1";
async function load(){const id=idParam();let data={id:"",item_name:"",item_type:"",rarity:"",probability:0,reward_coins:0,item_code:"",reward_exp:0,created_at:null};
 if(!isNew()){if(!id){notice("아이템 번호가 없습니다.");return}const {data:d,error}=await sb.from("dori_box_items").select("id,item_name,item_type,rarity,probability,reward_coins,item_code,created_at,reward_exp").eq("id",id).single();if(error){notice(error.message);return}data=d}
 render(data);
}
function notice(msg){$("#editorApp").innerHTML=`<div class="auth-error"><div>⚠️</div><h1>랜덤박스 편집기를 열 수 없습니다.</h1><p>${esc(msg)}</p><a class="primary" href="./index.html#box">랜덤박스 목록</a></div>`}
function render(d){const creating=isNew();$("#editorApp").innerHTML=`<div class="special-shell editor-only-shell"><header class="special-head"><div><button class="back-link" id="back">← 랜덤박스 목록</button><span class="eyebrow">RANDOM BOX / ${creating?"CREATE":"EDIT"}</span><h1>🎁 랜덤박스 아이템 ${creating?"생성":"수정"}</h1><p>${creating?"새 아이템을 추가합니다.":`아이템 #${esc(d.id)}를 편집합니다.`}</p></div><div class="editor-badge">${creating?"CREATE MODE":"EDIT MODE"}</div></header><div class="editor-layout"><section class="panel editor-main-card"><div class="editor-section-head"><div><span class="eyebrow">ITEM INFORMATION</span><h2>아이템 정보</h2></div>${creating?"":`<span class="id-chip">#${esc(d.id)}</span>`}</div><form id="boxForm" class="professional-form"><div class="form-grid two"><label>아이템 번호<input name="id" type="number" value="${esc(d.id)}" readonly placeholder="자동 생성"></label><label>아이템 이름<input name="item_name" required value="${esc(d.item_name)}"></label><label>아이템 타입<input name="item_type" value="${esc(d.item_type)}"></label><label>등급<input name="rarity" value="${esc(d.rarity)}"></label><label>아이템 코드<input name="item_code" value="${esc(d.item_code)}"></label><label>확률 (%)<input name="probability" type="number" min="0" max="100" step="0.01" required value="${Number(d.probability||0)}"></label><label>보상 돌돌코인<input name="reward_coins" type="number" min="0" step="1" value="${Number(d.reward_coins||0)}"></label><label>보상 EXP<input name="reward_exp" type="number" min="0" step="1" value="${Number(d.reward_exp||0)}"></label></div><div class="form-help">확률은 0~100%입니다. 저장 후 목록에서 전체 확률 합계를 확인할 수 있습니다.</div><div class="editor-actions"><button type="button" class="secondary" id="cancel">취소</button><button type="submit" class="primary" id="save">💾 ${creating?"아이템 생성":"변경사항 저장"}</button></div></form></section></div></div>`;$("#back").onclick=$("#cancel").onclick=()=>location.href="./index.html#box";$("#boxForm").onsubmit=save}
async function save(e){e.preventDefault();const f=e.currentTarget;const p={item_name:f.item_name.value.trim(),item_type:f.item_type.value.trim(),rarity:f.rarity.value.trim(),probability:Number(f.probability.value),reward_coins:Number(f.reward_coins.value||0),item_code:f.item_code.value.trim(),reward_exp:Number(f.reward_exp.value||0)};if(!p.item_name||!Number.isFinite(p.probability)||p.probability<0||p.probability>100||!Number.isInteger(p.reward_coins)||p.reward_coins<0||!Number.isInteger(p.reward_exp)||p.reward_exp<0){toast("입력값을 확인해 주세요.",false);return}const b=$("#save");b.disabled=true;b.textContent="저장 중…";try{const {data,error}=await sb.rpc("admin_save_box_item",{p_id:isNew()?null:Number(idParam()),p_item_name:p.item_name,p_item_type:p.item_type,p_rarity:p.rarity,p_probability:p.probability,p_reward_coins:p.reward_coins,p_item_code:p.item_code,p_reward_exp:p.reward_exp});if(error)throw error;toast(isNew()?"아이템이 생성되었습니다.":"아이템이 저장되었습니다.");setTimeout(()=>location.href="./index.html#box",450)}catch(err){b.disabled=false;b.textContent=isNew()?"💾 아이템 생성":"💾 변경사항 저장";toast(err.message||"저장에 실패했습니다.",false)}}
(async()=>{try{await requireAdmin();await load()}catch(e){notice(e.message)}})();
