const cfg=window.DORI_ADMIN_CONFIG||{};const sb=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);const $=s=>document.querySelector(s);const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
function toast(m,ok=true){const e=$("#toast");if(!e)return;e.textContent=m;e.className=ok?"show ok":"show";clearTimeout(window.__t);window.__t=setTimeout(()=>e.className="",2800)}
async function requireAdmin(){const {data,error}=await sb.auth.getSession();if(error||!data.session?.user)throw new Error("관리자 로그인 세션이 없습니다.");const {data:p,error:e}=await sb.from("users").select("is_admin,user_level,name").eq("user_id",String(data.session.user.id)).single();if(e)throw e;if(p?.is_admin!==true||Number(p.user_level||0)<10)throw new Error("관리자 권한이 없습니다.")}
const param=()=>new URLSearchParams(location.search).get("news_number");const creating=()=>new URLSearchParams(location.search).get("new")==="1";
async function load(){let d={news_number:"",enabled:true,event_name:"",description:"",reward_coins:0};if(!creating()){const n=param();if(!n){notice("이벤트 번호가 없습니다.");return}const {data,error}=await sb.from("rockey_news_events").select("news_number,enabled,event_name,description,reward_coins").eq("news_number",n).single();if(error){notice(error.message);return}d=data}render(d)}
function notice(m){$("#editorApp").innerHTML=`<div class="auth-error"><div>⚠️</div><h1>이벤트 편집기를 열 수 없습니다.</h1><p>${esc(m)}</p><a class="primary" href="./index.html#events">이벤트 목록</a></div>`}
function render(d){const c=creating();$("#editorApp").innerHTML=`<div class="special-shell editor-only-shell"><header class="special-head"><div><button class="back-link" id="back">← 이벤트 목록</button><span class="eyebrow">EVENT / ${c?"CREATE":"EDIT"}</span><h1>🎉 이벤트 ${c?"생성":"수정"}</h1><p>${c?"새 이벤트를 추가합니다.":`이벤트 #${esc(d.news_number)}를 편집합니다.`}</p></div><div class="editor-badge">${c?"CREATE MODE":"EDIT MODE"}</div></header><div class="editor-layout"><section class="panel editor-main-card"><div class="editor-section-head"><div><span class="eyebrow">EVENT INFORMATION</span><h2>이벤트 정보</h2></div>${c?"":`<span class="id-chip">#${esc(d.news_number)}</span>`}</div><form id="eventForm" class="professional-form"><div class="form-grid two"><label>이벤트 번호<input name="news_number" type="number" min="1" required ${c?"":"readonly"} value="${esc(d.news_number)}"></label><label>이벤트 이름<input name="event_name" required value="${esc(d.event_name)}"></label></div><label>이벤트 설명<textarea name="description" rows="10">${esc(d.description)}</textarea></label><label class="toggle-line professional-toggle"><input name="enabled" type="checkbox" ${d.enabled!==false?"checked":""}><span><b>이벤트 활성화</b><small>활성화 상태를 저장합니다.</small></span></label><label>보상 돌돌코인<input name="reward_coins" type="number" min="0" step="1" value="${Number(d.reward_coins||0)}"></label><div class="editor-actions"><button type="button" class="secondary" id="cancel">취소</button><button type="submit" class="primary" id="save">💾 ${c?"이벤트 생성":"변경사항 저장"}</button></div></form></section></div></div>`;$("#back").onclick=$("#cancel").onclick=()=>location.href="./index.html#events";$("#eventForm").onsubmit=save}
async function save(e){e.preventDefault();const f=e.currentTarget;const n=Number(f.news_number.value),p={news_number:n,event_name:f.event_name.value.trim(),description:f.description.value.trim(),enabled:f.enabled.checked,reward_coins:Number(f.reward_coins.value||0)};if(!Number.isInteger(n)||n<1||!p.event_name||!Number.isInteger(p.reward_coins)||p.reward_coins<0){toast("입력값을 확인해 주세요.",false);return}const b=$("#save");b.disabled=true;b.textContent="저장 중…";try{const {error}=await sb.rpc("admin_save_news_event",{p_old_news_number:creating()?null:Number(param()),p_news_number:n,p_enabled:p.enabled,p_event_name:p.event_name,p_description:p.description,p_reward_coins:p.reward_coins});if(error)throw error;toast(creating()?"이벤트가 생성되었습니다.":"이벤트가 저장되었습니다.");setTimeout(()=>location.href="./index.html#events",450)}catch(err){b.disabled=false;b.textContent=creating()?"💾 이벤트 생성":"💾 변경사항 저장";toast(err.message||"저장에 실패했습니다.",false)}}
(async()=>{try{await requireAdmin();await load()}catch(e){notice(e.message)}})();
